### ISSUE TITLE
weird timer issue

### ISSUE THREAD

**Issue by liamzebedee** [liamzebedee/vercel3-pipeline#6]
nondeterministic. occasionally the deployer fails mid-deploy with an issue related to timers, timeouts, idk.

**Comment by liamzebedee** [comment]
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at DeploymentManager.save (/Users/liamz/Documents/Projects/vercel3/cli/build/cmds/deploy.js:303:54)
    at DeploymentManager.addEvent (/Users/liamz/Documents/Projects/vercel3/cli/build/cmds/deploy.js:287:14)
    at Object.deploy [as handler] (/Users/liamz/Documents/Projects/vercel3/cli/build/cmds/deploy.js:673:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by liamzebedee** [comment]
fixed it. Turns out I was setting `proxy` on the `upsert_proxy` event, which is an ethers.Contract, which inevitably contained a Timer at some point due to async stuff which JSON can't serialise. removed it and it's good
